nelmio_cors:
    defaults:
        allow_origin: ['http://127.0.0.1:5173']  # Autorise uniquement cette origine spécifique
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        allow_credentials: true  # Permet les cookies et autres credentials
    paths:
        '^/api/':  # Applique la configuration uniquement aux routes API
            allow_origin: ['http://127.0.0.1:5173']  # Autorise l'origine de ton frontend uniquement
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['X-Total-Count']  # Si tu veux exposer d'autres headers
            max_age: 3600
            allow_credentials: true  # Permet les cookies et autres credentials
