nelmio_api_doc:
    documentation:
        info:
            title: Mon Api Symfony
            description: Documentation de l'API Symfony
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/doc # Accepts routes under /api except /api/doc
